# Generated by Django 5.1.2 on 2024-10-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0003_author_remove_genre_films_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='books',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='book',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Жанр'),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('genres', models.ManyToManyField(related_name='film', to='cinema_base.genre', verbose_name='Жанры')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
