# Generated by Django 5.1.2 on 2024-10-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0004_remove_book_author_remove_genre_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='film', to='cinema_base.genre', verbose_name='Жанры'),
        ),
    ]
