# Generated by Django 5.1.2 on 2024-10-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0005_alter_film_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='films', to='cinema_base.genre', verbose_name='Жанры'),
        ),
    ]
