# Generated by Django 5.1.2 on 2024-10-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0007_career_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='age',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guldence Suggested'), ('PG', 'Parental Guldence Suggested'), ('PG-13', 'Parents Strongly Caoutioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only'), ('NONE', 'None Information')], default='NONE', max_length=5),
        ),
    ]
