# Generated by Django 5.1.2 on 2024-10-10 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0008_film_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Студия')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='career',
        ),
        migrations.AddField(
            model_name='film',
            name='slogan',
            field=models.CharField(max_length=255, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='film',
            name='female_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='female_actor', to='cinema_base.actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='male_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='male_actor', to='cinema_base.actor'),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('films', models.ManyToManyField(blank=True, related_name='films', to='cinema_base.film', verbose_name='Фильм')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio', to='cinema_base.studio', verbose_name='Студия'),
        ),
        migrations.DeleteModel(
            name='Career',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
