# Generated by Django 5.1.2 on 2024-10-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0009_actor_studio_remove_person_career_film_slogan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default='1900-01-01', verbose_name='Дата рождения'),
        ),
    ]
