# Generated by Django 5.1.2 on 2024-10-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0010_actor_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Слоган'),
        ),
    ]
