# Generated by Django 5.1.2 on 2024-10-10 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0011_alter_film_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Оценка'),
        ),
    ]
