# Generated by Django 5.1.2 on 2024-10-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0013_film_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.DurationField(null=True, verbose_name='Длительность'),
        ),
    ]
