# Generated by Django 5.1.2 on 2024-10-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0014_alter_film_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(default='media/poster_none.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='film',
            name='release',
            field=models.DateField(default='1900-01-01', verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность'),
        ),
    ]
