# Generated by Django 5.1.2 on 2024-10-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0016_alter_actor_options_alter_director_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='None', max_length=6),
        ),
        migrations.AlterField(
            model_name='film',
            name='age',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guldence Suggested'), ('PG', 'Parental Guldence Suggested'), ('PG-13', 'Parents Strongly Caoutioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only'), ('NONE', 'None Information')], default='None', max_length=5),
        ),
    ]
