# Generated by Django 5.1.2 on 2024-10-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0020_remove_film_poster_alter_film_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(default='media/images/poster_none.jpg', upload_to='media/images'),
        ),
    ]
