# Generated by Django 5.1.2 on 2024-10-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0021_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.DurationField(blank=True, default='0:0:0', null=True, verbose_name='Длительность'),
        ),
    ]
