# Generated by Django 5.1.2 on 2024-10-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0024_alter_film_age_remove_film_genres_alter_film_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(default='None', max_length=6),
        ),
    ]
