# Generated by Django 5.1.2 on 2024-10-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0025_alter_actor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(default='длительность', max_length=255, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='film',
            name='female_actor',
            field=models.CharField(default='фемэйл', max_length=255, verbose_name='Женская роль'),
        ),
        migrations.AlterField(
            model_name='film',
            name='male_actor',
            field=models.CharField(default='мэйл', max_length=255, verbose_name='Мужская роль'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.CharField(default='рейтинг', max_length=255, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release',
            field=models.CharField(default='дата', max_length=255, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='studio',
            field=models.CharField(default='студия', max_length=255, verbose_name='Студия'),
        ),
    ]
