# Generated by Django 5.1.2 on 2024-10-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0026_alter_film_duration_alter_film_female_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guldence Suggested'), ('PG', 'Parental Guldence Suggested'), ('PG-13', 'Parents Strongly Caoutioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only'), ('NONE', 'None Information')], default='None', max_length=5),
        ),
    ]
