# Generated by Django 5.1.2 on 2024-10-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0027_alter_film_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='age',
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.DurationField(blank=True, default='00:00:00', verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='film',
            name='slogan',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Слоган'),
        ),
    ]
