# Generated by Django 5.1.2 on 2024-10-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0030_alter_film_male_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guldence Suggested'), ('PG', 'Parental Guldence Suggested'), ('PG-13', 'Parents Strongly Caoutioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only'), ('NONE', 'None Information')], default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='film',
            name='male_actor',
            field=models.CharField(default='мэйл', max_length=255, verbose_name='Мужская роль'),
        ),
    ]
