# Generated by Django 5.1.2 on 2024-10-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0031_alter_film_age_alter_film_male_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='age',
            field=models.CharField(default='возраст', max_length=20),
        ),
    ]
