# Generated by Django 5.1.2 on 2024-10-24 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0032_alter_film_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='None', max_length=6),
        ),
        migrations.AlterField(
            model_name='film',
            name='age',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guldence Suggested'), ('PG', 'Parental Guldence Suggested'), ('PG-13', 'Parents Strongly Caoutioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only'), ('NONE', 'None Information')], default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Оценка'),
        ),
    ]
