# Generated by Django 5.1.2 on 2024-10-24 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0033_alter_actor_gender_alter_film_age_alter_film_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio', to='cinema_base.studio', verbose_name='Студия'),
        ),
    ]
