# Generated by Django 5.1.2 on 2024-10-24 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0035_alter_film_male_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='female_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='female_actor', to='cinema_base.actor'),
        ),
    ]
