# Generated by Django 5.1.2 on 2024-10-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0036_alter_film_female_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release',
            field=models.DateField(default='1900-01-01', verbose_name='Дата выхода'),
        ),
    ]
