# Generated by Django 5.1.2 on 2024-10-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0038_alter_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(default='./images/poster_none.jpg', upload_to='./images'),
        ),
    ]
