# Generated by Django 5.1.2 on 2024-10-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0039_alter_film_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genres',
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='films', to='cinema_base.genre', verbose_name='Жанры'),
        ),
    ]
