# Generated by Django 5.1.2 on 2024-10-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0041_alter_film_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(default='./media/images/poster_none.jpg', upload_to='./media/images'),
        ),
    ]
