# Generated by Django 5.1.2 on 2024-10-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0043_alter_film_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(default='./media/images/poster_none.jpg', upload_to='media/images/peoples'),
        ),
    ]
