# Generated by Django 5.1.2 on 2024-10-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0046_alter_actor_photo_alter_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='films', to='cinema_base.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
