# Generated by Django 5.1.2 on 2024-10-25 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0047_alter_film_genres_alter_film_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='female_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='female_actor', to='cinema_base.actor'),
        ),
        migrations.AlterField(
            model_name='film',
            name='male_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='male_actor', to='cinema_base.actor'),
        ),
    ]
