# Generated by Django 5.1.2 on 2024-10-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_base', '0048_alter_film_female_actor_alter_film_male_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='films', to='cinema_base.genre', verbose_name='Жанры'),
        ),
    ]
